version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7

workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: echo "hey y'all!"